export const ActionTypes = {
  START_SCREEN_SAVER: 'START_SCREEN_SAVER',
  STOP_SCREEN_SAVER: 'STOP_SCREEN_SAVER',
  SHOW_PUPPIES: 'SHOW_PUPPIES',
  HIDE_PUPPIES: 'HIDE_PUPPIES',
  PUPPY_FELL_DOWN: 'PUPPY_FELL_DOWN'
};

export const numberOfPups = 6;
