export const DogActionTypes = {
  FETCH_DOG_REQUEST: 'FETCH_DOG_REQUEST',
  FETCH_DOG_LOADING: 'FETCH_DOG_LOADING',
  FETCH_DOG_SUCCESS: 'FETCH_DOG_SUCCESS',
  FETCH_DOG_FAILURE: 'FETCH_DOG_FAILURE'
};
